In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [16]:
#Load our dataframe account for the index columns
df = pd.read_csv('case_study.csv', index_col = 0)

In [17]:
# Quickly check to see the size of our DF, both rows and columns
df.shape

(34545, 358)

In [18]:
df.head()

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENM1,...,_PA300R2,_PA30021,_PASTRNG,_PAREC1,_PASTAE1,_RFSEAT2,_RFSEAT3,_FLSHOT6,_PNEUMO2,_AIDTST3
49938,9.0,5.0,5172017,5,17,2017,1200.0,2017000001,2.017000e+09,NaN,...,2.0,2.0,2.0,4.0,2.0,1.0,1.0,NaN,NaN,1.0
49939,9.0,2.0,2142017,2,14,2017,1200.0,2017000002,2.017000e+09,NaN,...,1.0,1.0,1.0,1.0,1.0,2.0,2.0,NaN,NaN,2.0
49940,9.0,1.0,1292017,1,29,2017,1200.0,2017000003,2.017000e+09,NaN,...,3.0,2.0,1.0,3.0,2.0,1.0,1.0,NaN,NaN,2.0
49941,9.0,7.0,9112017,9,11,2017,1200.0,2017000004,2.017000e+09,NaN,...,2.0,2.0,2.0,2.0,2.0,1.0,1.0,NaN,NaN,1.0
49942,9.0,5.0,7182017,7,18,2017,1200.0,2017000005,2.017000e+09,NaN,...,2.0,2.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,2.0

## Subset your dataframe to only include the states in the tri-state area (NJ, CT, NY)

In [23]:
# your code here
tristates = [9,34,36]
df[df['_STATE'].isin(tristates)]

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENM1,...,_PA300R2,_PA30021,_PASTRNG,_PAREC1,_PASTAE1,_RFSEAT2,_RFSEAT3,_FLSHOT6,_PNEUMO2,_AIDTST3
49938,9.0,5.0,5172017,5,17,2017,1200.0,2017000001,2.017000e+09,NaN,...,2.0,2.0,2.0,4.0,2.0,1.0,1.0,NaN,NaN,1.0
49939,9.0,2.0,2142017,2,14,2017,1200.0,2017000002,2.017000e+09,NaN,...,1.0,1.0,1.0,1.0,1.0,2.0,2.0,NaN,NaN,2.0
49940,9.0,1.0,1292017,1,29,2017,1200.0,2017000003,2.017000e+09,NaN,...,3.0,2.0,1.0,3.0,2.0,1.0,1.0,NaN,NaN,2.0
49941,9.0,7.0,9112017,9,11,2017,1200.0,2017000004,2.017000e+09,NaN,...,2.0,2.0,2.0,2.0,2.0,1.0,1.0,NaN,NaN,1.0
49942,9.0,5.0,7182017,7,18,2017,1200.0,2017000005,2.017000e+09,NaN,...,2.0,2.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,2.0
49943,9.0,1.0,1192017,1,19,2017,1100.0,2017000006,2.017000e+09,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,2.0
49944,9.0,1.0,2032017,2,3,2017,1100.0,2017000007,2.017000e+09,1.0,...,2.0,2.0,1.0,3.0,2.0,1.0,1.0,NaN,NaN,2.0
49945,9.0,1.0,2012017,2,1,2017,1100.0,2017000008,2.017000e+09,1.0,...,2.0,2.0,2.0,2.0,2.0,1.0,1.0,NaN,NaN,1.0
49946,9.0,1.0,1262017,1,26,2017,1100.0,2017000009,2.017000e+09,1.0,...,2.0,2.0,1.0,3.0,2.0,1.0,1.0,2.0,1.0,2.0
49947,9.0,1.0,1192017,1,19,2017,1100.0,2017000010,2.017000e+09,1.0,...,2.0,2.0,2.0,4.0,2.0,1.0,1.0,NaN,NaN,1.0
49948,9.0,1.0,1242017,1,24,2017,1100.0,2017000011,2.017000e+09,1.0,...,1.0,1.0,9.0,9.0,9.0,1.0,1.0,NaN,NaN,2.0
49949,9.0,1.0,1192017,1,19,2017,1100.0,2017000012,2.017000e+09,1.0,...,2.0,2.0,2.0,4.0,2.0,1.0,1.0,2.0,2.0,2.0
49950,9.0,1.0,1192017,1,19,2017,1100.0,2017000013,2.017000e+09,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,2.0
49951,9.0,1.0,1302017,1,30,2017,1100.0,2017000014,2.017000e+09,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0
49952,9.0,1.0,1262017,1,26,2017,1100.0,2017000015,2.017000e+09,1.0,...,2.0,2.0,2.0,4.0,2.0,1.0,1.0,NaN,NaN,2.0
49953,9.0,1.0,1202017,1,20,2017,1100.0,2017000016,2.017000e+09,1.0,...,2.0,2.0,2.0,4.0,2.0,1.0,1.0,NaN,NaN,2.0
49954,9.0,1.0,1212017,1,21,2017,1100.0,2017000017,2.017000e+09,1.0,...,2.0,2.0,1.0,3.0,2.0,1.0,1.0,NaN,NaN,2.0
49955,9.0,1.0,1312017,1,31,2017,1100.0,2017000018,2.017000e+09,1.0,...,1.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0
49956,9.0,1.0,1312017,1,31,2017,1200.0,2017000019,2.017000e+09,1.0,...,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,NaN
49957,9.0,1.0,1252017,1,25,2017,1100.0,2017000020,2.017000e+09,1.0,...,1.0,1.0,2.0,2.0,2.0,1.0,1.0,NaN,NaN,1.0
49958,9.0,1.0,1272017,1,27,2017,1100.0,2017000021,2.017000e+09,1.0,...,1.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,9.0,1.0
49959,9.0,1.0,1232017,1,23,2017,1100.0,2017000022,2.017000e+09,1.0,...,2.0,2.0,2.0,4.0,2.0,1.0,1.0,1.0,2.0,2.0
49960,9.0,1.0,1202017,1,20,2017,1100.0,2017000023,2.017000e+09,1.0,...,3.0,2.0,2.0,4.0,2.0,1.0,1.0,1.0,1.0,2.0
49961,9.0,1.0,1172017,1,17,2017,1100.0,2017000024,2.017000e+09,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,2.0
49962,9.0,1.0,1212017,1,21,2017,1100.0,2017000025,2.017000e+09,1.0,...,2.0,2.0,1.0,3.0,2.0,1.0,1.0,NaN,NaN,2.0
49963,9.0,1.0,1272017,1,27,2017,1100.0,2017000026,2.017000e+09,1.0,...,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0
49964,9.0,1.0,1252017,1,25,2017,1100.0,2017000027,2.017000e+09,1.0,...,3.0,2.0,2.0,4.0,2.0,1.0,1.0,2.0,2.0,2.0
49965,9.0,1.0,1272017,1,27,2017,1100.0,2017000028,2.017000e+09,1.0,...,1.0,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0
49966,9.0,1.0,2062017,2,6,2017,1100.0,2017000029,2.017000e+09,1.0,...,1.0,1.0,2.0,2.0,2.0,1.0,1.0,NaN,NaN,2.0
49967,9.0,1.0,1312017,1,31,2017,1100.0,2017000030,2.017000e+09,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
303749,36.0,6.0,6042017,6,4,2017,1200.0,2017012220,2.017012e+09,NaN,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,1.0
303750,36.0,6.0,6302017,6,30,2017,1200.0,2017012221,2.017012e+09,NaN,...,2.0,2.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,1.0
303751,36.0,6.0,6222017,6,22,2017,1200.0,2017012222,2.017012e+09,NaN,...,2.0,2.0,1.0,1.0,1.0,2.0,2.0,NaN,NaN,1.0
303752,36.0,6.0,6282017,6,28,2017,1200.0,2017012223,2.017012e+09,NaN,...,1.0,1.0,2.0,2.0,2.0,1.0,1.0,NaN,NaN,2.0
303753,36.0,7.0,8022017,8,2,2017,1200.0,2017012224,2.017012e+09,NaN,...,2.0,2.0,2.0,2.0,2.0,1.0,1.0,NaN,NaN,2.0
303754,36.0,7.0,7302017,7,30,2017,1200.0,2017012225,2.017012e+09,NaN,...,2.0,2.0,2.0,4.0,2.0,1.0,1.0,NaN,NaN,1.0
303755,36.0,7.0,7202017,7,20,2017,1200.0,2017012226,2.017012e+09,NaN,...,2.0,2.0,1.0,3.0,2.0,9.0,9.0,NaN,NaN,1.0
303756,36.0,8.0,8172017,8,17,2017,1200.0,2017012227,2.017012e+09,NaN,...,2.0,2.0,2.0,4.0,2.0,1.0,1.0,NaN,NaN,1.0
303757,36.0,8.0,8172017,8,17,2017,1200.0,2017012228,2.017012e+09,NaN,...,2.0,2.0,2.0,2.0,2.0,1.0,1.0,NaN,NaN,2.0
303758,36.0,10.0,10132017,10,13,2017,1200.0,2017012229,2.017012e+09,NaN,...,1.0,1.0,2.0,2.0,2.0,1.0,2.0,NaN,NaN,1.0
303759,36.0,10.0,10192017,10,19,2017,1200.0,2017012230,2.017012e+09,NaN,...,2.0,2.0,2.0,2.0,2.0,1.0,1.0,NaN,NaN,1.0
303760,36.0,12.0,12122017,12,12,2017,1200.0,2017012231,2.017012e+09,NaN,...,2.0,2.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,1.0
303761,36.0,7.0,7052017,7,5,2017,1200.0,2017012232,2.017012e+09,NaN,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,1.0
303762,36.0,1.0,1262017,1,26,2017,1200.0,2017012233,2.017012e+09,NaN,...,1.0,1.0,2.0,2.0,2.0,1.0,2.0,NaN,NaN,2.0
303763,36.0,2.0,2052017,2,5,2017,1200.0,2017012234,2.017012e+09,NaN,...,2.0,2.0,2.0,2.0,2.0,1.0,1.0,NaN,NaN,2.0
303764,36.0,4.0,5312017,5,31,2017,1200.0,2017012235,2.017012e+09,NaN,...,2.0,2.0,2.0,4.0,2.0,1.0,1.0,NaN,NaN,2.0
303765,36.0,6.0,6202017,6,20,2017,1200.0,2017012236,2.017012e+09,NaN,...,2.0,2.0,1.0,3.0,2.0,1.0,1.0,NaN,NaN,1.0
303766,36.0,7.0,8102017,8,10,2017,1200.0,2017012237,2.017012e+09,NaN,...,2.0,2.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,2.0
303767,36.0,7.0,8092017,8,9,2017,1200.0,2017012238,2.017012e+09,NaN,...,2.0,2.0,1.0,3.0,2.0,1.0,1.0,NaN,NaN,1.0
303768,36.0,9.0,10062017,10,6,2017,1200.0,2017012239,2.017012e+09,NaN,...,2.0,2.0,2.0,4.0,2.0,1.0,1.0,NaN,NaN,1.0
303769,36.0,1.0,2282017,2,28,2017,1200.0,2017012240,2.017012e+09,NaN,...,2.0,2.0,2.0,4.0,2.0,1.0,2.0,NaN,NaN,9.0
303770,36.0,1.0,2282017,2,28,2017,1200.0,2017012241,2.017012e+09,NaN,...,3.0,2.0,2.0,4.0,2.0,1.0,1.0,NaN,NaN,1.0
303771,36.0,2.0,3112017,3,11,2017,1200.0,2017012242,2.017012e+09,NaN,...,3.0,2.0,2.0,4.0,2.0,1.0,1.0,NaN,NaN,1.0
303772,36.0,3.0,4022017,4,2,2017,1200.0,2017012243,2.017012e+09,NaN,...,3.0,2.0,2.0,4.0,2.0,1.0,1.0,NaN,NaN,1.0
303773,36.0,4.0,4212017,4,21,2017,1200.0,2017012244,2.017012e+09,NaN,...,3.0,2.0,2.0,4.0,2.0,1.0,1.0,NaN,NaN,1.0
303774,36.0,5.0,5152017,5,15,2017,1200.0,2017012245,2.017012e+09,NaN,...,3.0,2.0,2.0,4.0,2.0,1.0,1.0,NaN,NaN,1.0
303775,36.0,6.0,6252017,6,25,2017,1200.0,2017012246,2.017012e+09,NaN,...,2.0,2.0,2.0,4.0,2.0,1.0,1.0,NaN,NaN,1.0
303776,36.0,7.0,7212017,7,21,2017,1200.0,2017012247,2.017012e+09,NaN,...,2.0,2.0,2.0,4.0,2.0,1.0,1.0,NaN,NaN,1.0
303777,36.0,7.0,7202017,7,20,2017,1200.0,2017012248,2.017012e+09,NaN,...,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0,9.0
303778,36.0,7.0,7252017,7,25,2017,1200.0,2017012249,2.017012e+09,NaN,...,3.0,2.0,2.0,4.0,2.0,1.0,1.0,NaN,NaN,1.0

Now check to see how large our subset df.

In [ ]:
# your code here

**PHYSHLTH** is the column we are interested in for this analysis, so let's start to investigate the column. Since we have a data cookbook, a.k.a. data dictionary) we want to start there before looking at the code.

In [29]:
df['PHYSHLTH'].describe()

count    33747.000000
mean         4.085341
std          8.513293
min          0.000000
25%          0.000000
50%          0.000000
75%          3.000000
max         30.000000
Name: PHYSHLTH, dtype: float64

## 1. Handle the non-normal values

As you can see from the data dictionary, there are a number of responses that are coded with values that could throw off our descriptive statistics.  Let's clean up by mapping the responses to a more appropriate value, and handling any missing values.

In [26]:
#your code here
zero_dict = {88:0, 77: np.nan, 99: np.nan}
df['PHYSHLTH'] = df['PHYSHLTH'].replace(zero_dict)

In [31]:
df['PHYSHLTH'].describe().index

Index(['count', 'mean', 'std', 'min', '25%', '50%', '75%', 'max'], dtype='object')

## 2. Generate the descriptive statistics

Now that our target variable is cleaned up lets calculate the descriptive statistics, generate a graph that quickly shows those statistics, and generate a gprah shows the histogram of the data.

In [11]:
# descriptive statistics

In [ ]:
# graphic showing those descriptive stats

In [ ]:
# graphic showing the distribution of data

## 3. Generate a graphic that compares the average number of sick days for each state.

In [ ]:
# code to calculate the average number of sick days by state

In [ ]:
# code to graph those averages using matplotlib

## 4. Turn the number of sick days into a classification of of chronically sick people.  

Chronically sick people account for a significant proportion of the costs for health insurers. If we can identify what leads people to be chronically sick, we can address them with specific treatments.

In [16]:
# code to create new colum for chronically sick

## 5. Create a graphic that compares the percentage of people labeled as 'sick' in each state.

In [ ]:
# code to calculate averages per state

In [ ]:
# create graphic to compare chronically sick by state

## 6. Independent Variables (categorical)

Let's take the column `SMOKDAY2` and start to prepare it so that we can see how it is possibly correlated to `PHYSHLTH`.

1. Clean up the values.
2. Calculate the descriptive statistics of the variable.
3. Generate a histogram for the variable.
4. Generate graphics that show how the responses to this variable might differ by state.
5. Generate a graphic that compares the physical health of the different groups of 'smokers'.

## 7. Independent Variables (continuous):

Now let's look at a continuous variable (ALCDAY5) and see how that might impact a person's health. 

1. Clean up the values.
2. Calculate the descriptive statistics of the variable.
3. Generate a histogram for the variable.
4. Generate graphics that show how the responses to this variable might differ by state.
5. Calculate the correlation coefficient between `PHYSHLTH` and `ALCDAY5`.
5. Generate a graphic that shows the possible relationship between `PHYSHLTH` and `ALCDAY5`.

## 8. Additional variables: Choose two additional survey items you would like to investigate do steps  6 or 7 for those variables.

In [34]:
# your code here
nan == Null

NameError: name 'nan' is not defined

## 9. Based on your initial data exploration, what are some hypotheses of what affects a person's health that you would like to further investigate?

Type out your initial hyptotheses below:

1. 

2. 

3.

## Bonus: Create some cool graphics.